<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dashboard | GeoCustomer Analytics</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
body{background:#f5f7fb;color:#172033}.navbar{box-shadow:0 4px 18px rgba(15,23,42,.08)}.stat-card{border:0;border-radius:18px;overflow:hidden;box-shadow:0 8px 26px rgba(15,23,42,.07);height:100%;transition:transform .18s ease,box-shadow .18s ease}.stat-card:hover{transform:translateY(-3px);box-shadow:0 12px 32px rgba(15,23,42,.11)}.stat-icon{width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.25rem;background:#eef4ff;color:#0d6efd}.stat-value{font-size:1.8rem;font-weight:800;line-height:1}.section-card{border:0;border-radius:18px;box-shadow:0 8px 26px rgba(15,23,42,.06)}.quick-action{border:0;border-radius:12px!important;margin-bottom:8px;background:#f8fafc}.quick-action:hover{background:#eef4ff}.table>:not(caption)>*>*{padding:.85rem .75rem}
</style>
</head>
<body>
<nav class="navbar navbar-dark bg-primary py-3"><div class="container-fluid px-3 px-lg-5"><span class="navbar-brand fw-bold"><i class="bi bi-geo-alt-fill me-2"></i>GeoCustomer Analytics</span><div class="text-white d-flex align-items-center gap-3"><span class="d-none d-md-inline">Welcome, <strong><?= htmlspecialchars($user['full_name']) ?></strong></span><a href="logout.php" class="btn btn-light btn-sm"><i class="bi bi-box-arrow-right me-1"></i>Logout</a></div></div></nav>
<div class="container-fluid px-3 px-lg-5 py-4">
<div class="mb-4"><div class="text-primary small fw-semibold text-uppercase">Overview</div><h2 class="fw-bold mb-1">Dashboard</h2><p class="text-muted mb-0">A quick view of your customer distribution data.</p></div>
<div class="row g-4 mb-4">
<?php $cards=[['Total Customers',$stats['customers'],'bi-people-fill','Manage your customer records.','customer_list.php'],['States',$stats['states'],'bi-map-fill','States represented in your data.','map.php'],['This Month',$stats['monthly'],'bi-calendar-check-fill','Customers added this month.','customer_create.php'],['Top Area',$stats['topLocation'],'bi-pin-map-fill','Most represented customer state.','map.php']]; foreach($cards as $card): ?>
<div class="col-sm-6 col-xl-3"><a href="<?= htmlspecialchars($card[4]) ?>" class="text-decoration-none text-reset"><div class="card stat-card"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start"><div><div class="text-muted small mb-2"><?= htmlspecialchars($card[0]) ?></div><div class="stat-value mb-2"><?= htmlspecialchars((string)$card[1]) ?></div><div class="small text-muted"><?= htmlspecialchars($card[3]) ?></div></div><div class="stat-icon"><i class="bi <?= htmlspecialchars($card[2]) ?>"></i></div></div></div></div></a></div>
<?php endforeach; ?>
</div>
<div class="row g-4"><div class="col-xl-8"><div class="card section-card"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="fw-bold mb-1">Recent Customers</h5><p class="text-muted small mb-0">Latest records added to the system.</p></div><a href="customer_list.php" class="btn btn-sm btn-outline-primary">View all</a></div><?php if(empty($recentCustomers)): ?><div class="text-center py-5 text-muted"><i class="bi bi-people fs-1 d-block mb-2"></i>No customers yet.</div><?php else: ?><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Customer</th><th>Phone</th><th>Location</th></tr></thead><tbody><?php foreach($recentCustomers as $customer): ?><tr><td class="fw-semibold"><?= htmlspecialchars(trim($customer['first_name'].' '.$customer['last_name'])) ?></td><td><?= htmlspecialchars($customer['phone']??'—') ?></td><td><?= htmlspecialchars(trim(($customer['city']??'').', '.($customer['state']??''))) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
<div class="col-xl-4"><div class="card section-card"><div class="card-body p-4"><h5 class="fw-bold mb-1">Quick Actions</h5><p class="text-muted small mb-3">Common tasks at your fingertips.</p><div class="list-group"><a href="customer_create.php" class="list-group-item quick-action"><i class="bi bi-person-plus-fill text-primary me-2"></i>Add Customer</a><a href="customer_list.php" class="list-group-item quick-action"><i class="bi bi-people-fill text-primary me-2"></i>Customer List</a><a href="map.php" class="list-group-item quick-action"><i class="bi bi-geo-alt-fill text-primary me-2"></i>Customer Map</a><a href="analytics.php" class="list-group-item quick-action"><i class="bi bi-bar-chart-fill text-primary me-2"></i>Analytics</a></div></div></div></div>
</div></div>
</body></html>
